Web/Controllers/AnnouncementController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using DataContext.Data;
using DataContext.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Models;
using Web.Models.Announcements;

namespace Web.Controllers
{
    [Authorize]
    public class AnnouncementController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AnnouncementController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new AnnouncementIndexModel
            {
                Announcements = _context.Announcements
                    .Include(x => x.Category)
                    .Include(x => x.User)
                    .OrderByDescending(x => x.PublishedAt)
                    .ToList()
            };
            
            return View(model);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            var model = new ManageAnnouncementModel
            {
                Announcement = new Announcement(),
                AnnouncementCategories = _context.AnnouncementCategories.ToList()
            };
            
            return View("Edit", model);
        }
        
        [HttpPost]
        public IActionResult Store(Announcement announcement)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            announcement.User = _context.Users.Single(x => x.Id == userId);
            announcement.Category = _context.AnnouncementCategories.Single(x => x.Id == announcement.Category.Id);

            _context.Announcements.Add(announcement);
            _context.SaveChanges();


            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int announcementId)
        {
            var model = new ManageAnnouncementModel
            {
                Announcement = _context.Announcements.Include(x => x.Category).Single(x => x.Id == announcementId),
                AnnouncementCategories = _context.AnnouncementCategories.ToList()
            };
            
            return View(model);
        }
        
        [HttpPost]
        public IActionResult Update(Announcement announcement, int announcementId)
        {
            var persistedAnnouncement = _context.Announcements.Single(x => x.Id == announcementId);
            persistedAnnouncement.Body = announcement.Body;
            persistedAnnouncement.Category = _context.AnnouncementCategories.Single(x => x.Id == announcement.Category.Id);

            _context.Announcements.Update(persistedAnnouncement);
            _context.SaveChanges();
            
            return RedirectToAction("Edit", new {announcementId});
        }
        
        [HttpGet]
        public IActionResult Delete(int announcementId)
        {
            var announcement = _context.Announcements.Single(x => x.Id == announcementId);
            _context.Announcements.Remove(announcement);

            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }
    }
}

Web/Controllers/EventController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using DataContext.Data;
using DataContext.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Models;
using Web.Models.Announcements;
using Web.Models.Events;

namespace Web.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new EventIndexModel
            {
                Events = _context.Events.ToList()
            };
            
            return View(model);
        }
        
        [HttpGet]
        public IActionResult Create()
        {
            var model = new ManageEventModel
            {
                Event = new Event()
            };
            
            return View("Edit", model);
        }
        [HttpPost]
        public IActionResult Store(Event @event)
        {
            _context.Events.Add(@event);
            _context.SaveChanges();


            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public IActionResult Edit(int eventId)
        {
            var model = new ManageEventModel
            {
                Event = _context.Events.Single(x => x.Id == eventId),
            };
            
            return View(model);
        }
        
        [HttpPost]
        public IActionResult Update(Event @event, int eventId)
        {
            var persistedEvent = _context.Events.Single(x => x.Id == eventId);
            persistedEvent.Name = @event.Name;
            persistedEvent.DateTime = @event.DateTime;

            _context.Events.Update(persistedEvent);
            _context.SaveChanges();
            
            return RedirectToAction("Edit", new {eventId});
        }
        
        [HttpGet]
        public IActionResult Delete(int eventId)
        {
            var @event = _context.Events.Single(x => x.Id == eventId);
            _context.Events.Remove(@event);

            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }
    }
}

Web/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using DataContext.Data;
using DataContext.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Web.Models;
using Web.Models.Announcements;
using Web.Models.Products;

namespace Web.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new ProductIndexModel
            {
                Products = _context.Products
                    .Include(x => x.Tasks)
                    .ThenInclude(x => x.Status)
                    .ToList()
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var model = new ManageProductModel()
            {
                Product = new Product(),
                TaskStatuses = _context.TaskStatuses.ToList()
            };

            return View("Edit", model);
        }

        [HttpPost]
        public IActionResult Store(Product product)
        {
            product.Tasks = product.Tasks.Select(task => new Task
            {
                Name = task.Name,
                Status = _context.TaskStatuses.Single(x => x.Id == task.Status.Id)
            }).ToList();

            _context.Products.Add(product);
            _context.SaveChanges();


            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int productId)
        {
            var model = new ManageProductModel
            {
                Product = _context.Products.Include(x => x.Tasks).ThenInclude(x => x.Status)
                    .Single(x => x.Id == productId),
                TaskStatuses = _context.TaskStatuses.ToList()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Update(Product product, int productId)
        {
            var persistedProduct = _context.Products.Include(x => x.Tasks).Single(x => x.Id == productId);
            persistedProduct.Name = product.Name;

            var latestTasksForProduct = product.Tasks.Select(x => x.Id);
            var tasksToDelete = persistedProduct.Tasks.Where(x => !latestTasksForProduct.Contains(x.Id));

            _context.Tasks.RemoveRange(tasksToDelete);

            product.Tasks.ForEach(task =>
            {
                var isNewTask = task.Id < 1;

                var taskToPersist = isNewTask ? new Task() : _context.Tasks.Single(x => x.Id == task.Id);
                taskToPersist.Name = task.Name;
                taskToPersist.Status = _context.TaskStatuses.Single(x => x.Id == task.Status.Id);

                if (isNewTask)
                {
                    persistedProduct.Tasks.Add(taskToPersist);
                }

                var _ = isNewTask
                    ? _context.Tasks.Add(taskToPersist)
                    : _context.Tasks.Update(taskToPersist);
            });


            _context.SaveChanges();


            return RedirectToAction("Edit", new {productId});
        }

        public IActionResult Delete(int productId)
        {
            var product = _context.Products.Include(x => x.Tasks).Single(x => x.Id == productId);

            product.Tasks.Clear();
            
            _context.Products.Remove(product);
            _context.SaveChanges();
            
            return RedirectToAction("Index");
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="wide-container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Announcement" asp-action="Index">Announcements</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="wide-container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>